import Head from 'next/head'
import Header from '../Modules/Header'

import { AppProvider } from '../context/AppProvider'
import { useState } from "react"
import PrincipalView from '../Modules/PrincipalView'

const Home = ()=> {
  const [isActive,setIsActive] = useState(false);

    // STARS : BsStarFill BsStarHalf BsStar 
  // Favorite ICON: BsBookmarkStarFill


  return (
    <>
        <Head>
          <title>MovieSite || Home </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <PrincipalView></PrincipalView>
    </>
  )
}

export default Home
